MVC_Assignments/Assignment1/Assignment1/Assignment1/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Assignment1.Models
{
    public class Contact
    {
        public long Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }
    }
}

MVC_Assignments/Assignment1/Assignment1/Assignment1/Models/ContactContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Assignment1.Models
{
    public class ContactContext:DbContext
    {
        public ContactContext() : base("name= connectstr") { }

        public DbSet<Contact> Contacts { get; set; }
    }
}

MVC_Assignments/Assignment1/Assignment1/Assignment1/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment1.Models;
using Assignment1.Repositories;
using System.Threading.Tasks;

namespace Assignment1.Controllers
{
    public class ContactsController : Controller
    {
        // GET: Contacts
        IContactRepository repository;
        public ContactsController()
        {
            repository = new ContactRepository();
        }
        public async Task<ActionResult> Index()
        {
            var contacts = await repository.GetAllAsync();
            return View(contacts);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Contact contact)
        {
            if (ModelState.IsValid)
            {
                await repository.CreateAsync(contact);
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(long id)
        {
            await repository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

MVC_Assignments/Assignment1/Assignment1/Assignment1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_Assignments/Assignment1/Assignment1/Assignment1/Views/Contacts/Create.cshtml
@model Assignment1.Models.Contact

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h2>Create Contact</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
  <label>First Name:</label>
   @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
@Html.ValidationMessageFor(m => m.FirstName)
<br />
<label>Last Name:</label>
@Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
@Html.ValidationMessageFor(m => m.LastName)
<br /> 
<label>Email:</label>
@Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
@Html.ValidationMessageFor(m => m.Email)
<br /> 
<button type="submit" class="btn btn-primary">Create</button>}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Assignments/Assignment1/Assignment1/Assignment1/Views/Contacts/Index.cshtml
@model IEnumerable<Assignment1.Models.Contact>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
   

            @using (Html.BeginForm("Delete", "Contacts", FormMethod.Post))
            {
        @Html.Hidden("id", item.Id)
<button type="submit" class="btn btn-danger">Delete</button>}
        </td>
    </tr>
}

</table>